### ISSUE TITLE
Petsc error

### ISSUE THREAD

**Issue by cprakashj01** [seamplex/feenox#7] opened 2021-09-06 16:27 UTC
I am trying to install feenox on Ubuntu-20.04. 

I followed the installation process detailed on the website using Git repository.
I get the following error when run 'make'

In file included from ./feenox.h:69,
                 from ./feenox.c:22:
/usr/lib/petscdir/petsc3.12/x86_64-linux-gnu-real/include/petscsys.h:167:6: error: #error "PETSc was configured with OpenMPI but now appears to be compiling using a non-OpenMPI mpi.h"

Could someone please help me figure out how to fix this?

**Comment by jeremyonscale** [comment] 2021-09-06 16:42
Hi. This is odd as this means that PETSc has been linked against OpenMPI but FeenoX is using headers from MPICH. Hinestly I thought this would be managed automatically if everythibg comes from packaged PETSc, but it does not seem to be the case.

The first thing to try is to uninstall any MPI implementation that is not OpenMPI. This might break some other installed oackages  but it is temporary just to check if FeenoX compiles or not. Use you favorite package manager and leave installed only the MPI implementation that the PETSc library as provided by Ubuntu was linked against, which seems to be OpenMPI.

Then we'll see how to proceed.

**Comment by gtheler** [comment] 2021-09-06 18:55
I'm trying to reproduce this in a Vagrant image with Ubuntu 20.04 and I can compile FeenoX as expected.
I have installed both `libopenmpi-dev` and `libmpich-dev` along with `petsc-dev` and everything goes smooth.

What packages named `lib*mpi*` do you have installed?

```
vagrant@ubuntu2004:~/feenox$ dpkg -l "lib*mpi*"
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name                                Version                 Architecture Description
+++-===================================-=======================-============-==============================================================>
un  libblacs-mpi-dev                    <none>                  <none>       (no description available)
ii  libcaf-openmpi-3:amd64              2.8.0-1                 amd64        Co-Array Fortran libraries  (OpenMPI)
ii  libcoarrays-openmpi-dev:amd64       2.8.0-1                 amd64        Co-Array Fortran libraries  - development files (OpenMPI)
ii  libfftw3-mpi-dev:amd64              3.3.8-2ubuntu1          amd64        MPI Library for computing Fast Fourier Transforms - development
ii  libfftw3-mpi3:amd64                 3.3.8-2ubuntu1          amd64        MPI Library for computing Fast Fourier Transforms
ii  libhdf5-mpi-dev                     1.10.4+repack-11ubuntu1 amd64        Hierarchical Data Format 5 (HDF5) - development files - defaul>
un  libhdf5-openmpi-100                 <none>                  <none>       (no description available)
ii  libhdf5-openmpi-103:amd64           1.10.4+repack-11ubuntu1 amd64        Hierarchical Data Format 5 (HDF5) - runtime files - OpenMPI ve>
ii  libhdf5-openmpi-dev                 1.10.4+repack-11ubuntu1 amd64        Hierarchical Data Format 5 (HDF5) - development files - OpenMP>
ii  libmpich-dev:amd64                  3.3.2-2build1           amd64        Development files for MPICH
ii  libmpich12:amd64                    3.3.2-2build1           amd64        Shared libraries for MPICH
ii  libopenmpi-dev:amd64                4.0.3-0ubuntu1          amd64        high performance message passing library -- header files
ii  libopenmpi3:amd64                   4.0.3-0ubuntu1          amd64        high performance message passing library -- shared library
ii  libscalapack-mpi-dev:amd64          2.1.0-2build1           amd64        Scalable Linear Algebra Package - Dev files for MPI
un  libscalapack-mpi1                   <none>                  <none>       (no description available)
ii  libscalapack-openmpi-dev:amd64      2.1.0-2build1           amd64        Scalable Linear Algebra Package - Dev files for OpenMPI
ii  libscalapack-openmpi2.1:amd64       2.1.0-2build1           amd64        Scalable Linear Algebra Package - Shared libs for OpenMPI
ii  libsundials-nvecparallel-mpi3:amd64 3.1.2+dfsg-3ubuntu2     amd64        MPI vector operations library (SUNDIALS library)
```

**Comment by cprakashj01** [comment] 2021-09-06 18:58
Here's my lib*mpi* packages
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name                                Version                 Architecture Description
+++-===================================-=======================-============-==========================================>
un  libblacs-mpi-dev                    <none>                  <none>       (no description available)
ii  libboost-mpi-dev                    1.71.0.0ubuntu2         amd64        C++ interface to the Message Passing Inter>
ii  libboost-mpi-python-dev             1.71.0.0ubuntu2         amd64        C++ interface to the Message Passing Inter>
un  libboost-mpi-python1.40.0           <none>                  <none>       (no description available)
un  libboost-mpi-python1.41.0           <none>                  <none>       (no description available)
un  libboost-mpi-python1.42-dev         <none>                  <none>       (no description available)
un  libboost-mpi-python1.42.0           <none>                  <none>       (no description available)
un  libboost-mpi-python1.46-dev         <none>                  <none>       (no description available)
un  libboost-mpi-python1.46.0           <none>                  <none>       (no description available)
un  libboost-mpi-python1.46.1           <none>                  <none>       (no description available)
un  libboost-mpi-python1.48-dev         <none>                  <none>       (no description available)
un  libboost-mpi-python1.48.0           <none>                  <none>       (no description available)
un  libboost-mpi-python1.49-dev         <none>                  <none>       (no description available)
un  libboost-mpi-python1.49.0           <none>                  <none>       (no description available)
un  libboost-mpi-python1.50-dev         <none>                  <none>       (no description available)
un  libboost-mpi-python1.50.0           <none>                  <none>       (no description available)
un  libboost-mpi-python1.52-dev         <none>                  <none>       (no description available)
un  libboost-mpi-python1.52.0           <none>                  <none>       (no description available)
un  libboost-mpi-python1.53-dev         <none>                  <none>       (no description available)
un  libboost-mpi-python1.53.0           <none>                  <none>       (no description available)
un  libboost-mpi-python1.54-dev         <none>                  <none>       (no description available)
un  libboost-mpi-python1.54.0           <none>                  <none>       (no description available)
un  libboost-mpi-python1.55-dev         <none>                  <none>       (no description available)
un  libboost-mpi-python1.55.0           <none>                  <none>       (no description available)

**Comment by gtheler** [comment] 2021-09-06 19:15
You have both `libmpich-dev` and `libopenmpi-dev` installed as I do in my Vagrant box above. But for some reason PETSc is choosing the MPICH headers instead of the OpenMPI ones. Please uninstall `libopenmpi-dev` temporarily and then re-configure and re-compile FeenoX. If this works, then we'll have to see how to update the alternatives to force FeenoX to choose the MPI version used in the Ubuntu PETSc package.

**Comment by cprakashj01** [comment] 2021-09-06 19:31
So, I removed `libopenmpi-dev` and reinstalled it. Then I configured feenox again and now when I run `make` I get this error:

```
./pdes/neutron_diffusion/post.c: In function ‘feenox_problem_solve_post_neutron_diffusion’:
./pdes/neutron_diffusion/post.c:31:62: error: ‘struct <anonymous>’ has no member named ‘eigenvalue’
   31 |     feenox_var_value(neutron_diffusion.keff) = 1.0/feenox.pde.eigenvalue[0];
      |                                                              ^
./pdes/neutron_diffusion/post.c:33:58: error: ‘struct <anonymous>’ has no member named ‘eigenvalue’
   33 |     feenox_var_value(neutron_diffusion.keff) = feenox.pde.eigenvalue[0];
      |                                                          ^
make[1]: *** [Makefile:2341: pdes/neutron_diffusion/feenox-post.o] Error 1
```

**Comment by gtheler** [comment] 2021-09-06 19:33
Ok, we're good. That's a bug in FeenoX when using PETSc but not SLEPc.
I'll fix it and come back to you.

**Comment by cprakashj01** [comment] 2021-09-06 19:33
Thank you.

**Comment by gtheler** [comment] 2021-09-06 19:41
I fixed that in 868dbb779114f0afc8f47640021b93d3c9c53d17 but I'm not sure if that bug was causing that error.
Make sure you pull and re-autogen again:

```
git pull
./autogen.sh
./configure
```

Show me the summary of dependencies in `configure` .

**Comment by cprakashj01** [comment] 2021-09-06 19:51
So, it looks like the configuration was successful, and the `make check` gives the following:

```
============================================================================
Testsuite summary for feenox v0.1.47-g868dbb7
============================================================================
# TOTAL: 28
# PASS:  17
# SKIP:  10
# XFAIL: 1
# FAIL:  0
# XPASS: 0
# ERROR: 0
============================================================================
```

But when I run an example, it says:
```
feenox beam-cantilever.fee
error: beam-cantilever.fee: 2: FeenoX is not compiled with PETSc so it cannot solve PROBLEMs
```

I am not sure why it would not compile with PETSc.
Is there a specific version I should be using?

**Comment by gtheler** [comment] 2021-09-06 19:55
That's the thing that I found odd in the last error you posted and that's why I asked you to post the summary of dependencies after running `configure`. Note that the summary you posted is for the `make check` and there you can see that there were 10 skipped tests because the `feenox` executable you got is not linked against PETSc.

Post this part of the `configure` output:

```
## ----------------------- ##
## Summary of dependencies ##
## ----------------------- ##
  GNU Scientific Library  from system
  SUNDIALS                yes
  PETSc                   yes /home/gtheler/libs/petsc-3.15.0 arch-linux2-c-debug
  SLEPc                   yes /home/gtheler/libs/slepc-3.15.1
```

**Comment by cprakashj01** [comment] 2021-09-06 19:58
I see. Yes it doesn't include PETSc here:

```
## ----------------------- ##
## Summary of dependencies ##
## ----------------------- ##
  GNU Scientific Library  from system
  SUNDIALS                no
  PETSc                   no
  SLEPc                   no
```

**Comment by gtheler** [comment] 2021-09-06 20:00
Maybe you accidentally unistalled `libpetsc-dev` when uninstalling `libmpich-dev`. Try all over again. Make sure you have `libpetsc-dev` installed and only one MPI implementation.

**Comment by cprakashj01** [comment] 2021-09-06 20:18
So now I reinstalled `sudo apt-get install libsundials-dev petsc-dev slepc-dev` and reconfigured to get this:
```
## ----------------------- ##
## Summary of dependencies ##
## ----------------------- ##
  GNU Scientific Library  from system
  SUNDIALS                yes
  PETSc                   yes /usr/lib/petsc
  SLEPc                   yes /usr/lib/slepc
```
But then I again get the error `"PETSc was configured with OpenMPI but now appears to be compiling using a non-OpenMPI mpi.h"`

If I remove `libopenmpi-dev`, it removes all it's dependencies including PETSc. It seems auto-installation using `sudo apt-get install libsundials-dev petsc-dev slepc-dev` always installs with open-mpi. The output of this command is:
```
Setting up libopenmpi-dev:amd64 (4.0.3-0ubuntu1) ...
update-alternatives: using /usr/lib/x86_64-linux-gnu/openmpi/include to provide /usr/include/x86_64-linux-gnu/mpi (mpi-x86_64-linux-gnu) in auto mode
```
I don't know if I have to manually install PETSc?

**Comment by gtheler** [comment] 2021-09-06 20:22
Right, you have to remove `libmpich-dev` not `libopenmpi-dev`.

**Comment by cprakashj01** [comment] 2021-09-06 20:28
Yes, I did that as well. 
```
sudo apt-get remove libmpich-dev
Package 'libmpich-dev' is not installed, so not removed
```
I removed `libmpich-dev` and kept `libopenmpi-dev` and have the same error.

**Comment by gtheler** [comment] 2021-09-06 20:48
I don't know then. See if this is of any help: https://stackoverflow.com/questions/66535019/switch-from-mpich-to-openmpi
I think the problem comes from the fact that `mpicc` points to something that is not OpenMPI's `mpicc`.

This is what I have in a fake Ubuntu 20.04 box:

```
vagrant@ubuntu2004:~$ which mpicc
/usr/bin/mpicc
vagrant@ubuntu2004:~$ ls -la /usr/bin/mpicc
lrwxrwxrwx 1 root root 21 Sep  6 18:43 /usr/bin/mpicc -> /etc/alternatives/mpi
vagrant@ubuntu2004:~$ ls -la /etc/alternatives/mpi
lrwxrwxrwx 1 root root 22 Sep  6 18:43 /etc/alternatives/mpi -> /usr/bin/mpicc.openmpi
vagrant@ubuntu2004:~$ 
```

In my native Debian, I have PETSc compiled from scratch deliberately using mpich instead of openmpi:

```
gtheler@tom:~$ which mpicc
/usr/bin/mpicc
gtheler@tom:~$ ls -la /usr/bin/mpicc
lrwxrwxrwx 1 root root 21 Apr 15 10:33 /usr/bin/mpicc -> /etc/alternatives/mpi
gtheler@tom:~$ ls -la /etc/alternatives/mpi
lrwxrwxrwx 1 root root 20 Sep  6 16:34 /etc/alternatives/mpi -> /usr/bin/mpicc.mpich
gtheler@tom:~$ 
```

**Comment by gtheler** [comment] 2021-09-06 22:13
What do you have for `which mpicc`, `ls -la $(which mpicc)` and so on @cprakashj01 ?

**Comment by cprakashj01** [comment] 2021-09-06 22:16
I have `openmpi` instead of `mpich` for `mpicc`
```
which mpicc
/opt/intel/oneapi/mpi/2021.2.0//bin/mpicc

ls -la /usr/bin/mpicc
lrwxrwxrwx 1 root root 21 Dec 18  2020 /usr/bin/mpicc -> /etc/alternatives/mpi

ls -la /etc/alternatives/mpi
lrwxrwxrwx 1 root root 22 Dec 18  2020 /etc/alternatives/mpi -> /usr/bin/mpicc.openmpi
```

**Comment by gtheler** [comment] 2021-09-06 22:28
So the whole thing comes from Intel sniffing around. Your default is to use Intel's MPI, neither OpenMPI nor MPICH. Your `mpicc` points to ` /opt/intel/oneapi/mpi/2021.2.0//bin/mpicc` which is a binary, not a symbolic link. I was following the links in my posts above. There is nothing that link `mpicc` to `mpicc.openmpi` in your system.

I cannot help you with the detailes there, but there are two rough alternatives:
 1. get rid of the Intel `mpicc` so you can compile FeenoX with the PETSc provided by Ubuntu (which was compiled with OpenMPI and not with Intel MPI), or
 2. compile PETSc with Intel MPI so you can compile FeenoX with your current `mpicc`

Let us know how it goes.

**Comment by gtheler** [comment] 2021-09-06 22:49
Also you can just temporarily rename `/opt/intel/oneapi/mpi/2021.2.0//bin/mpicc` to something else and make sure `which mpicc` points to `mpicc.openmpi` and re-configure FeenoX.

**Comment by cprakashj01** [comment] 2021-09-07 03:03
Thank you. It works. I renamed `/opt/intel/oneapi/mpi/2021.2.0//bin/mpicc` and then re-configured FeenoX.

**Comment by gtheler** [comment] 2021-09-07 13:59
Good it works. I'll try to see if I can add a message in `configure` saying what `mpicc` resolves to so we can catch issues like this one (i.e. having Intell MPI installed without knowing) before. I'll close the issue after I add this check.

**Closed** 2021-09-07 17:37 UTC

**Comment by gtheler** [comment] 2021-09-07 19:24
@cprakashj01 if you have any question about using FeenoX, please use https://github.com/seamplex/feenox/discussions
