### ISSUE TITLE
Multiple volumes and materials

### ISSUE THREAD

**Issue by skbizport** [seamplex/feenox#15] opened 2023-05-04 17:53 UTC
Hi

Would be great if you could add an example (.fee file) of how to specify multiple volumes and materials and then solve a problem. Also how to extract stress results per volume. 

I have a multi-body CAD part as input and boundary condition can span faces across bodies.

Regards
SK

**Comment by gtheler** [comment] 2023-05-04 21:31
Good point. I thought there was already an example. Will add one ASAP. For now, you can see one example for thermal conduction in section 2.6 of the SDS https://www.seamplex.com/feenox/doc/sds.html#sec:flexibility
Also check these files in the `test` directory

 * `reflected-src.fee`
 * `reed.fee`
 * `two-cubes-orthotropic-materials.fee`
 * `2dpwr.fee`
 * `thermal-two-squares-material-explicit-uniform.fee`
 * `materials.fee`
 * `thermal-two-squares-material-explicit-temperature.fee`
 * `thermal-two-squares-material-explicit-space.fee`
 * `two-cubes-isotropic-materials.fee`
 * `encased_rod_lr.fee`
 * `encased_rod_tb.fee`
 * `thermal-two-squares-material-implicit-space.fee`
 * `thermal-two-squares-material-implicit-temperature.fee`
 * `thermal-two-squares-material-implicit-uniform.fee`
 * `two-cubes-isotropic-functions.fee`
 * `two-cubes-isotropic-variables.fee`

Let me know if you need any help.

**Comment by skbizport** [comment] 2023-05-04 21:48
Really appreciated!

Thx

**Comment by gtheler** [comment] 2023-05-05 12:46
I had forgotten that there was already one thermal example with two different materials: https://seamplex.com/feenox/examples/thermal.html#non-dimensional-transient-heat-conduction-with-time-dependent-properties

I'll add an example for mechanical with the same mesh and using the `MATERIAL` keyword instead of the `property_material` scheme.

Let me know how it goes.

**Comment by skbizport** [comment] 2023-05-05 13:56
Sure. 

Currently I am using following

MATERIAL material_1 E=10000000 nu=0.3
MATERIAL material_2 E=20000000 nu=0.2

Where material_1 and material_2 are volume tags in the mesh file.
Hope that's how we map the two.

Another question would be how to generate 2 separate result files (e.g vtk or CSV with simulation results) for each of the 2 volumes.

Thx

**Comment by gtheler** [comment] 2023-05-05 14:06
ok, that works although I don't like seeing to many zeroes because I don't know if I'm missing one or have one more than I should. 
An alternative would be

```
E_material_1 = 1e7
nu_material_1 = 0.3
E_material_2 = 2e7
nu_material_2 = 0.2
```

There are implementation differences so performance might be slightly different, but shouldn't be noticeable.

In principle filtering out results by volumes is a post-processing step and by design it's not implemented in FeenoX.
You can do something like this, although this will fail at the interface:

```
WRITE_MESH one.vtk sigma(x,y,z)*(equal(nu(x,y,z)=0.3)
WRITE_MESH two.vtk sigma(x,y,z)*(equal(nu(x,y,z)=0.2)
```

**Comment by skbizport** [comment] 2023-05-05 14:40
Ok.

Alternatively, assigning a material to a stress value will work as well and allow easier post processing if it supported, something like 

WRITE_MESH results.vtk sigma <some way to add material or volume index like 1, 2 or even name>

Thx

**Comment by gtheler** [comment] 2023-05-05 14:48
You can do all that in the post-processing step, either in ParaView or using PyVista or Gmsh, etc.
Explain what you want to achieve and I'll tell you what the best way to do it is.

**Comment by skbizport** [comment] 2023-05-05 16:19
Use case is to generate a varying lattice structure (e.g. change beam radius of FCC lattice as a function of stress or displacement), or any other FEA result. 

Input to this process would be a CAD model with multiple bodies, say 2 separate but touching bodies. Post simulation, each of these 2 bodies will need its own lattice structure generated based on the stress. These bodies will use different lattice structures. So, post processing steps need to be able to distinguish results by bodies.

Hope this helps.

Thx
SK

**Comment by gtheler** [comment] 2023-05-05 21:35
See if this example matches what you need: https://www.seamplex.com/feenox/examples/mechanical.html#two-cubes-compressing-each-other

If it does, let's close this issue.

Again, if you show me more details I'll be able to provide some guidance.

**Comment by skbizport** [comment] 2023-05-06 13:48
This should work. Let me verify and confirm. I can drop a separate note on what I am trying to achieve - If there is a contact email.

Thank you so much in putting this together. 

Regards
SK

**Comment by gtheler** [comment] 2023-05-06 18:35
Sure, drop me a line at jeremy at seamplex dot com

**Closed** 2023-05-08 13:04 UTC
